/*
 * CARMIN a Common web API for Remote pipeline INvocation
 * FLI/IAM REST API for exchanging data and remote calling pipelines.
 *
 * OpenAPI spec version: 0.2.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fr.insalyon.creatis.vip.java_client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DeleteExecutionConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-23T15:07:38.469+02:00")
public class DeleteExecutionConfiguration {
  @SerializedName("deleteFiles")
  private Boolean deleteFiles = null;

  public DeleteExecutionConfiguration deleteFiles(Boolean deleteFiles) {
    this.deleteFiles = deleteFiles;
    return this;
  }

   /**
   * Get deleteFiles
   * @return deleteFiles
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getDeleteFiles() {
    return deleteFiles;
  }

  public void setDeleteFiles(Boolean deleteFiles) {
    this.deleteFiles = deleteFiles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteExecutionConfiguration deleteExecutionConfiguration = (DeleteExecutionConfiguration) o;
    return Objects.equals(this.deleteFiles, deleteExecutionConfiguration.deleteFiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deleteFiles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteExecutionConfiguration {\n");
    
    sb.append("    deleteFiles: ").append(toIndentedString(deleteFiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

