/*
 * CARMIN a Common web API for Remote pipeline INvocation
 * FLI/IAM REST API for exchanging data and remote calling pipelines.
 *
 * OpenAPI spec version: 0.2.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fr.insalyon.creatis.vip.client.processing.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


/**
 * Gets or Sets ParameterType
 */
public enum ParameterType {
  
  @SerializedName("File")
  FILE("File"),
  
  @SerializedName("String")
  STRING("String"),
  
  @SerializedName("Boolean")
  BOOLEAN("Boolean"),
  
  @SerializedName("Int64")
  INT64("Int64"),
  
  @SerializedName("Double")
  DOUBLE("Double"),
  
  @SerializedName("List")
  LIST("List");

  private String value;

  ParameterType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }
}

