/*
 * CARMIN a Common web API for Remote pipeline INvocation
 * FLI/IAM REST API for exchanging data and remote calling pipelines.
 *
 * OpenAPI spec version: 0.2.1
 * Contact: carmin@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fr.insalyon.creatis.vip.java_client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import fr.insalyon.creatis.vip.java_client.model.ErrorCodeAndMessage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * PlatformProperties
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-19T11:01:11.364+02:00")
public class PlatformProperties {
  @SerializedName("platformName")
  private String platformName = null;

  @SerializedName("APIErrorCodesAndMessages")
  private List<ErrorCodeAndMessage> apIErrorCodesAndMessages = new ArrayList<ErrorCodeAndMessage>();

  /**
   * Gets or Sets supportedTransferProtocols
   */
  public enum SupportedTransferProtocolsEnum {
    @SerializedName("http")
    HTTP("http"),
    
    @SerializedName("https")
    HTTPS("https"),
    
    @SerializedName("ftp")
    FTP("ftp"),
    
    @SerializedName("sftp")
    SFTP("sftp"),
    
    @SerializedName("ftps")
    FTPS("ftps"),
    
    @SerializedName("scp")
    SCP("scp"),
    
    @SerializedName("webdav")
    WEBDAV("webdav");

    private String value;

    SupportedTransferProtocolsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("supportedTransferProtocols")
  private List<SupportedTransferProtocolsEnum> supportedTransferProtocols = new ArrayList<SupportedTransferProtocolsEnum>();

  /**
   * Gets or Sets supportedModules
   */
  public enum SupportedModulesEnum {
    @SerializedName("Processing")
    PROCESSING("Processing"),
    
    @SerializedName("Data")
    DATA("Data"),
    
    @SerializedName("Management")
    MANAGEMENT("Management"),
    
    @SerializedName("Commercial")
    COMMERCIAL("Commercial");

    private String value;

    SupportedModulesEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("supportedModules")
  private List<SupportedModulesEnum> supportedModules = new ArrayList<SupportedModulesEnum>();

  @SerializedName("defaultLimitListExecutions")
  private Long defaultLimitListExecutions = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("platformDescription")
  private String platformDescription = null;

  @SerializedName("minAuthorizedExecutionTimeout")
  private Long minAuthorizedExecutionTimeout = null;

  @SerializedName("maxAuthorizedExecutionTimeout")
  private Long maxAuthorizedExecutionTimeout = null;

  @SerializedName("defaultExecutionTimeout")
  private Long defaultExecutionTimeout = null;

  @SerializedName("isKillExecutionSupported")
  private Boolean isKillExecutionSupported = null;

  @SerializedName("unsupportedMethods")
  private List<String> unsupportedMethods = new ArrayList<String>();

  @SerializedName("defaultStudy")
  private String defaultStudy = null;

  @SerializedName("supportedAPIVersion")
  private String supportedAPIVersion = null;

  public PlatformProperties platformName(String platformName) {
    this.platformName = platformName;
    return this;
  }

   /**
   * Name of the platform.
   * @return platformName
  **/
  @ApiModelProperty(example = "null", value = "Name of the platform.")
  public String getPlatformName() {
    return platformName;
  }

  public void setPlatformName(String platformName) {
    this.platformName = platformName;
  }

  public PlatformProperties apIErrorCodesAndMessages(List<ErrorCodeAndMessage> apIErrorCodesAndMessages) {
    this.apIErrorCodesAndMessages = apIErrorCodesAndMessages;
    return this;
  }

  public PlatformProperties addApIErrorCodesAndMessagesItem(ErrorCodeAndMessage apIErrorCodesAndMessagesItem) {
    this.apIErrorCodesAndMessages.add(apIErrorCodesAndMessagesItem);
    return this;
  }

   /**
   * Get apIErrorCodesAndMessages
   * @return apIErrorCodesAndMessages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ErrorCodeAndMessage> getApIErrorCodesAndMessages() {
    return apIErrorCodesAndMessages;
  }

  public void setApIErrorCodesAndMessages(List<ErrorCodeAndMessage> apIErrorCodesAndMessages) {
    this.apIErrorCodesAndMessages = apIErrorCodesAndMessages;
  }

  public PlatformProperties supportedTransferProtocols(List<SupportedTransferProtocolsEnum> supportedTransferProtocols) {
    this.supportedTransferProtocols = supportedTransferProtocols;
    return this;
  }

  public PlatformProperties addSupportedTransferProtocolsItem(SupportedTransferProtocolsEnum supportedTransferProtocolsItem) {
    this.supportedTransferProtocols.add(supportedTransferProtocolsItem);
    return this;
  }

   /**
   * Protocol names must be URL prefixes (e.g. \"http\", \"https\", \"ftp\", \"sftp\", \"ftps\", \"scp\", \"webdav\").
   * @return supportedTransferProtocols
  **/
  @ApiModelProperty(example = "null", required = true, value = "Protocol names must be URL prefixes (e.g. \"http\", \"https\", \"ftp\", \"sftp\", \"ftps\", \"scp\", \"webdav\").")
  public List<SupportedTransferProtocolsEnum> getSupportedTransferProtocols() {
    return supportedTransferProtocols;
  }

  public void setSupportedTransferProtocols(List<SupportedTransferProtocolsEnum> supportedTransferProtocols) {
    this.supportedTransferProtocols = supportedTransferProtocols;
  }

  public PlatformProperties supportedModules(List<SupportedModulesEnum> supportedModules) {
    this.supportedModules = supportedModules;
    return this;
  }

  public PlatformProperties addSupportedModulesItem(SupportedModulesEnum supportedModulesItem) {
    this.supportedModules.add(supportedModulesItem);
    return this;
  }

   /**
   * Get supportedModules
   * @return supportedModules
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<SupportedModulesEnum> getSupportedModules() {
    return supportedModules;
  }

  public void setSupportedModules(List<SupportedModulesEnum> supportedModules) {
    this.supportedModules = supportedModules;
  }

  public PlatformProperties defaultLimitListExecutions(Long defaultLimitListExecutions) {
    this.defaultLimitListExecutions = defaultLimitListExecutions;
    return this;
  }

   /**
   * The number of Executions returned by getExecutions
   * @return defaultLimitListExecutions
  **/
  @ApiModelProperty(example = "null", value = "The number of Executions returned by getExecutions")
  public Long getDefaultLimitListExecutions() {
    return defaultLimitListExecutions;
  }

  public void setDefaultLimitListExecutions(Long defaultLimitListExecutions) {
    this.defaultLimitListExecutions = defaultLimitListExecutions;
  }

  public PlatformProperties email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public PlatformProperties platformDescription(String platformDescription) {
    this.platformDescription = platformDescription;
    return this;
  }

   /**
   * Get platformDescription
   * @return platformDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlatformDescription() {
    return platformDescription;
  }

  public void setPlatformDescription(String platformDescription) {
    this.platformDescription = platformDescription;
  }

  public PlatformProperties minAuthorizedExecutionTimeout(Long minAuthorizedExecutionTimeout) {
    this.minAuthorizedExecutionTimeout = minAuthorizedExecutionTimeout;
    return this;
  }

   /**
   * Get minAuthorizedExecutionTimeout
   * @return minAuthorizedExecutionTimeout
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMinAuthorizedExecutionTimeout() {
    return minAuthorizedExecutionTimeout;
  }

  public void setMinAuthorizedExecutionTimeout(Long minAuthorizedExecutionTimeout) {
    this.minAuthorizedExecutionTimeout = minAuthorizedExecutionTimeout;
  }

  public PlatformProperties maxAuthorizedExecutionTimeout(Long maxAuthorizedExecutionTimeout) {
    this.maxAuthorizedExecutionTimeout = maxAuthorizedExecutionTimeout;
    return this;
  }

   /**
   * 0 or absent means no max timeout. max has to be greater or equal to the min.
   * @return maxAuthorizedExecutionTimeout
  **/
  @ApiModelProperty(example = "null", value = "0 or absent means no max timeout. max has to be greater or equal to the min.")
  public Long getMaxAuthorizedExecutionTimeout() {
    return maxAuthorizedExecutionTimeout;
  }

  public void setMaxAuthorizedExecutionTimeout(Long maxAuthorizedExecutionTimeout) {
    this.maxAuthorizedExecutionTimeout = maxAuthorizedExecutionTimeout;
  }

  public PlatformProperties defaultExecutionTimeout(Long defaultExecutionTimeout) {
    this.defaultExecutionTimeout = defaultExecutionTimeout;
    return this;
  }

   /**
   * Get defaultExecutionTimeout
   * @return defaultExecutionTimeout
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDefaultExecutionTimeout() {
    return defaultExecutionTimeout;
  }

  public void setDefaultExecutionTimeout(Long defaultExecutionTimeout) {
    this.defaultExecutionTimeout = defaultExecutionTimeout;
  }

  public PlatformProperties isKillExecutionSupported(Boolean isKillExecutionSupported) {
    this.isKillExecutionSupported = isKillExecutionSupported;
    return this;
  }

   /**
   * Get isKillExecutionSupported
   * @return isKillExecutionSupported
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getIsKillExecutionSupported() {
    return isKillExecutionSupported;
  }

  public void setIsKillExecutionSupported(Boolean isKillExecutionSupported) {
    this.isKillExecutionSupported = isKillExecutionSupported;
  }

  public PlatformProperties unsupportedMethods(List<String> unsupportedMethods) {
    this.unsupportedMethods = unsupportedMethods;
    return this;
  }

  public PlatformProperties addUnsupportedMethodsItem(String unsupportedMethodsItem) {
    this.unsupportedMethods.add(unsupportedMethodsItem);
    return this;
  }

   /**
   * List of optional methods that are not supported by the platform. Must be consistent with the \"isKillExecutionSupported\" property.
   * @return unsupportedMethods
  **/
  @ApiModelProperty(example = "null", value = "List of optional methods that are not supported by the platform. Must be consistent with the \"isKillExecutionSupported\" property.")
  public List<String> getUnsupportedMethods() {
    return unsupportedMethods;
  }

  public void setUnsupportedMethods(List<String> unsupportedMethods) {
    this.unsupportedMethods = unsupportedMethods;
  }

  public PlatformProperties defaultStudy(String defaultStudy) {
    this.defaultStudy = defaultStudy;
    return this;
  }

   /**
   * Get defaultStudy
   * @return defaultStudy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultStudy() {
    return defaultStudy;
  }

  public void setDefaultStudy(String defaultStudy) {
    this.defaultStudy = defaultStudy;
  }

  public PlatformProperties supportedAPIVersion(String supportedAPIVersion) {
    this.supportedAPIVersion = supportedAPIVersion;
    return this;
  }

   /**
   * Get supportedAPIVersion
   * @return supportedAPIVersion
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSupportedAPIVersion() {
    return supportedAPIVersion;
  }

  public void setSupportedAPIVersion(String supportedAPIVersion) {
    this.supportedAPIVersion = supportedAPIVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlatformProperties platformProperties = (PlatformProperties) o;
    return Objects.equals(this.platformName, platformProperties.platformName) &&
        Objects.equals(this.apIErrorCodesAndMessages, platformProperties.apIErrorCodesAndMessages) &&
        Objects.equals(this.supportedTransferProtocols, platformProperties.supportedTransferProtocols) &&
        Objects.equals(this.supportedModules, platformProperties.supportedModules) &&
        Objects.equals(this.defaultLimitListExecutions, platformProperties.defaultLimitListExecutions) &&
        Objects.equals(this.email, platformProperties.email) &&
        Objects.equals(this.platformDescription, platformProperties.platformDescription) &&
        Objects.equals(this.minAuthorizedExecutionTimeout, platformProperties.minAuthorizedExecutionTimeout) &&
        Objects.equals(this.maxAuthorizedExecutionTimeout, platformProperties.maxAuthorizedExecutionTimeout) &&
        Objects.equals(this.defaultExecutionTimeout, platformProperties.defaultExecutionTimeout) &&
        Objects.equals(this.isKillExecutionSupported, platformProperties.isKillExecutionSupported) &&
        Objects.equals(this.unsupportedMethods, platformProperties.unsupportedMethods) &&
        Objects.equals(this.defaultStudy, platformProperties.defaultStudy) &&
        Objects.equals(this.supportedAPIVersion, platformProperties.supportedAPIVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(platformName, apIErrorCodesAndMessages, supportedTransferProtocols, supportedModules, defaultLimitListExecutions, email, platformDescription, minAuthorizedExecutionTimeout, maxAuthorizedExecutionTimeout, defaultExecutionTimeout, isKillExecutionSupported, unsupportedMethods, defaultStudy, supportedAPIVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlatformProperties {\n");
    
    sb.append("    platformName: ").append(toIndentedString(platformName)).append("\n");
    sb.append("    apIErrorCodesAndMessages: ").append(toIndentedString(apIErrorCodesAndMessages)).append("\n");
    sb.append("    supportedTransferProtocols: ").append(toIndentedString(supportedTransferProtocols)).append("\n");
    sb.append("    supportedModules: ").append(toIndentedString(supportedModules)).append("\n");
    sb.append("    defaultLimitListExecutions: ").append(toIndentedString(defaultLimitListExecutions)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    platformDescription: ").append(toIndentedString(platformDescription)).append("\n");
    sb.append("    minAuthorizedExecutionTimeout: ").append(toIndentedString(minAuthorizedExecutionTimeout)).append("\n");
    sb.append("    maxAuthorizedExecutionTimeout: ").append(toIndentedString(maxAuthorizedExecutionTimeout)).append("\n");
    sb.append("    defaultExecutionTimeout: ").append(toIndentedString(defaultExecutionTimeout)).append("\n");
    sb.append("    isKillExecutionSupported: ").append(toIndentedString(isKillExecutionSupported)).append("\n");
    sb.append("    unsupportedMethods: ").append(toIndentedString(unsupportedMethods)).append("\n");
    sb.append("    defaultStudy: ").append(toIndentedString(defaultStudy)).append("\n");
    sb.append("    supportedAPIVersion: ").append(toIndentedString(supportedAPIVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

